### ISSUE TITLE
Version - WARN

### ISSUE THREAD

**Issue by BeanBagKing** [jrivard/pwm#1]
I started getting a warning that PWM could not check the current version on August 1st. 

> Unable to check PWM current version: 5054 ERROR_UNREACHABLE_CLOUD_SERVICE (unable to reach version check service 'https://pwm-cloud.appspot.com/rest/pwm/current-version', error: peer not authenticated)

Visiting pwm-cloud.appspot.com gives me what looks like good version information.
> {"build":"1232","version":"v1.7.1"}

At the very least the site does exist, and the build number and version match what I am on. Any guesses as to the problem?

**Comment by jrivard** [comment]
'peer not authenticated' is an ssl error.  Your java keystore doesnt have a ca cert that matches the cloud service's ssl cert.
