### ISSUE TITLE
Manual setup doesn't work in commit 7b8c1396f663d2a8a20e1b23edb58e9a2f835b23

### ISSUE THREAD

**Issue by joernott** [jrivard/pwm#12]
Hello,

as the guided setup does not work for my setup (searching for "groupMembership" instead of "memberOf" and no way to change it), I tried the manual setup. When clicking on the button and confirming with "OK", I get redirected to the guide again.

**Comment by jrivard** [comment]
Which LDAP directory are you usingthat uses memberOf?

**Comment by joernott** [comment]
It is OpenLDAP with a few schema extensions (e.g. for Zimbra) and we have PWM 1.7.1 already working with it. In that version, we have the following setting:
<setting key="pwmAdmin.queryMatch" syntax="STRING">
      <label>Administrator Query String</label>
      <value><![CDATA[(memberof=cn=pwm-admin,ou=groups,dc=<cut>)]]></value>
    </setting>

But I have no way of importing the old config or do a manual setup toe even be able to specify that setting.

**Comment by jrivard** [comment]
Fixed manual in latest commit, as well I created an OpenLDAP config template and set the group value attribute to 'memberof'.
