### ISSUE TITLE
User Registration Filtering

### ISSUE THREAD

**Issue by jeeftor** [jrivard/pwm#3]
I'm trying to make PWM only allow certain email addresses to sign up.  If i'm correct this is done via:

    </setting>
      <setting key="activateUser.queryMatch" syntax="STRING">
         <label>Activation Query Match</label>
        <value><![CDATA[(&(loginDisabled=true)(!(vehicleInformation=pwmActivated))(|(mail=*@gmail.com)(mail=*@hotmail.com)))]]></value>
    </setting>

So I have this in my PWM and i tried to sign up with a gmail account.  It appears to not work (which is good) but there is no display to the user or anything saying this is an invalid email.  I just never got a registration code by email.

Is this the expected behavior?

**Comment by jrivard** [comment]
Please ask for help on the pwm google group
