### ISSUE TITLE
Session token may be filtered by input validator

### ISSUE THREAD

**Issue by thoutenbos** [jrivard/pwm#4]
What steps will reproduce the problem?
1. get a random session token from PWM
2. follow the redirect to validate your client
3. the session token after the redirect will be filtered if it contains the string "href"

What version of PWM are you using?
trunk

Please paste any error log messages below:

The session validation token contains the keyword “href” which is considered malicious by the input validator, therefore the input is discarded before the session validator can process it and the user ends in a redirect loop.

2015-03-06 07:55:39, WARN , pwm.Validator, removing potentially malicious string values from input, converting 'vUzSjfRR2RNB2t**HReF**JnzKhmwNJw25nt14bedde39f2' newValue=' pattern='(?s)(?i).href.'

**Comment by jrivard** [comment]
Fixed in trunk.  Thanks for the bug report,
