### ISSUE TITLE
Using external change method for sambaNTPassword and sambaLMPassword

### ISSUE THREAD

**Issue by ASzczesniak** [jrivard/pwm#5]
Hi, I spent lot of time configuring PWM for company's self service and the only thing lacking is way to change these two fields in LDAP for samba. Is there any way it can be added to configuration? I'm not a developer, so I have no clue how to write java class on my own. I'm sure that there are already methods for encrypting passwords for these fields, but I'm still not sure how should I implement it.

**Comment by jrivard** [comment]
Please ask for help on the pwm google group.
