### ISSUE TITLE
Admin filter is broken

### ISSUE THREAD

**Issue by dejayc** [jrivard/pwm#6]
I'm another user on Java 1.8 with the latest version of PWM that cannot get admin filter to work, no matter what.  Even entering simple values (cn=admin, etc.) doesn't work at all.  I've spent about TWELVE hours trying to get this to work by playing with each and every permutation I could discover, so any help would be appreciated.

According to the following read-only bug, this issue doesn't seem to have existed in version 1.7.1:

https://code.google.com/p/pwm/issues/detail?id=669

I wish I could try version 1.7.1 out for comparison, but I'm not able to use Java 1.7 at the moment.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google gorup.
