### ISSUE TITLE
Redirect to captcha JSP doesn't work because of mismatch of paths in web.xml and servlet

### ISSUE THREAD

**Issue by clifford-github** [jrivard/pwm#7]
Hi,

when I activate 'Login Form' and 'Forgotten Password' in 'CAPTCHA Protected Pages' and open https://localhost:8443/pwm/ I'm redirected to https://localhost:8443/pwm/private/login and not to the captcha page.
If I click on the 'Forgotten Password' button I get redirected to https://localhost:8443/pwm/public/forgottenpassword.

I looked at the CaptchaFilter in web.xml

```
<filter-mapping>
    <filter-name>CaptchaFilter</filter-name>
    <url-pattern>/private/Login</url-pattern>
    ...
    <url-pattern>/public/ForgottenPassword</url-pattern>
    ...
</filter-mapping>
```

So I tried https://localhost:8443/pwm/private/Login and https://localhost:8443/pwm/public/ForgottenPassword. In both instances I get redirected to the captcha page https://localhost:8443/pwm/public/captcha

When I change the CaptchaFilter to 

```
<filter-mapping>
    <filter-name>CaptchaFilter</filter-name>
    <url-pattern>/private/login</url-pattern>
    ...
    <url-pattern>/public/forgottenpassword</url-pattern>
    ...
</filter-mapping>
```

it works.

I'm using pwm-20150824-0600.war, Tomcat 7, OS X Yosemite.

Regards

Clifford

**Comment by jrivard** [comment]
Should be fixed in the trunk now.
