### ISSUE TITLE
Install Docs

### ISSUE THREAD

**Issue by eperry** [jrivard/pwm#8]
The screen shots look great but I don't see anything to help me do an initial deployment.
This looks java based - standard Tomcat/Jboss?

I see in the Release build both the exploded directory structure and a war file.  Do I need just the War file or both deployed?

**Comment by cananda** [comment]
http://pwm.googlecode.com/svn/trunk/pwm/supplemental/PWMAdministrationGuide.pdf

I found this guide.  It's a bit involved to get this going and I wish there was a simple way to integrate with OpenLDAP.

**Comment by eperry** [comment]
That seems more like the info I need thanks.  Maybe a link from main page to tell others would be nice

**Comment by jrivard** [comment]
Please ask for help in the pwm-general google group.
